models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

  - type: llama_topic_guard
    engine: nim_openai
    parameters:
      openai_api_base: "http://localhost:8000/v1/"
      model_name: "llama-3.1-topic-guard"
      chat_model: true

rails:
  input:
    flows:
      - topic safety check input $model="llama_topic_guard"
