models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

  - type: topic_control
    engine: nim
    parameters:
      base_url: "http://localhost:8000/v1/"
      model_name: "llama-3.1-nemoguard-8b-topic-control"

rails:
  input:
    flows:
      - topic safety check input $model=topic_control
