models:
  - type: main
    engine: openai
    model: text-davinci-003

rails:
  input:
    flows:
      # - check jailbreak
      - active fence moderation detailed
  output:
    flows:
      - check facts
      - output moderation
      - check hallucination
