instructions:
  - type: general
    content: |
      Below is a conversation between a bot and a user. The bot is talkative and
      precise. If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hello there!"
    express greeting
  bot express greeting
    "Hello! What would you like assistance with today?"
  user "What can you do for me?"
    ask about capabilities
  bot respond about capabilities
    "This assistant is built to showcase features of NeMo Guardrails. It's designed to stay on topic, and to not respond to an unethical question, not give unethical answers, not present false information as true, and not use sensitive phrases!"
  user "What's 2+2?"
    ask math question
  bot responds to math question
    "2+2 is equal to 4."
  user "Tell me a bit about the US Bureau of Labor Statistics."
    ask question about publisher
  bot response for question about publisher
    "The Bureau of Labor Statistics is the principal fact-finding agency for the Federal Government in the broad field of labor economics and statistics"
  user "thanks"
    express appreciation
  bot express appreciation and offer additional help
    "You're welcome. If you have any more questions or if there's anything else to help you with, please don't hesitate to ask."

models:
  - type: main
    engine: openai
    model: text-davinci-003

rails:
  input:
    flows:
      - check jailbreak
      - active fence moderation detailed
  output:
    flows:
      - check facts
      - output moderation
      - check hallucination
