models:
  - type: main
    engine: openai
    model: text-davinci-003

custom_data:
  fact_checking:
    provider: align_score  # or ask_llm
    parameters:
      endpoint: "http://localhost:5000/alignscore_large"
