models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

  - type: "llama_3.1_aegis_guard_2.0"
    engine: vllm_openai
    parameters:
      openai_api_base: "http://localhost:8123/v1"
      model_name: "llama-3.1-aegis-guard-2.0"

rails:
  input:
    flows:
      - content safety check input $model=llama_3.1_aegis_guard_2.0
  output:
    flows:
      - content safety check output $model=llama_3.1_aegis_guard_2.0
