name: Full Tests

on:
  pull_request:
    types: [review_requested, ready_for_review]
    paths-ignore:
      - "**/*.md"
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  call-tests:
    strategy:
      matrix:
        os: [Ubuntu, Windows, macOS]
        python-version: ["3.9", "3.10", "3.11"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-2022
          - os: macOS
            image: macos-14
      fail-fast: false

    uses: ./.github/workflows/_test.yml
    with:
      os: ${{ matrix.os }}
      image: ${{ matrix.image }}
      python-version: ${{ matrix.python-version }}
