name: "Lock Closed Threads"

on:
  schedule:
    - cron: "0 0 * * *" # 12:00 midnight UTC, daily

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lock-issues:
    if: github.repository_owner == 'NVIDIA'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@v5
        with:
          process-only: issues
          issue-inactive-days: 30
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs and reference this issue there.

  lock-prs:
    if: github.repository_owner == 'NVIDIA'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: dessant/lock-threads@v5
        with:
          process-only: prs
          pr-inactive-days: 30
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue and reference this PR there.
